version: "3"
services:
  client:
    build:
      context: ./client
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=https://server-o3uc.onrender.com
      # For running a ci pipeline in github when the project is ready or if others begin to work on project
      # - CI=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
  server:
    build:
      context: ./server
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
  database:
    build:
      context: ./database
    volumes:
      - form-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  form-volume:
