version: "3"
services:
  client:
    build:
      context: ./client
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000
      # For running a ci pipeline in github when the project is ready or if others begin to work on project
      # - CI=true
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./server/.env
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
  database:
    build:
      context: ./database
    volumes:
      - form-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  form-volume:
