version: 3
services:
  server:
    build:
      context: ./server
      ports:
        - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - SERVER_PORT=5001
