services:
# React - Client
  - type: web
    name: client
    env: static
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
    # Getting enVars from api
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: server
          envVarKey: RENDER_EXTERNAL_URL
# Api - Server
  - type: web
    name: server
    env: docker # Will read api Dockerfile?
    rootDir: server
    region: singapore
    envVars:
      - key: API_PORT
        value: 200 # Any port will do.
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
    plan: free
# Database
databases:
  - name: database
    region: singapore
    plan: free
    ipAllowList: [] # What does this do?

