const topic_data = [
  {
    topic_id: 2,
    title: "Star Wars",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Movies",
    post_id: [1, 2],
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },

  {
    topic_id: 3,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 4,
    title: "Tabletop",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Games",
    post_id: 77,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 5,
    title: "Events",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Community",
    post_id: 17,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 6,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 7,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 8,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 9,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 10,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 11,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 12,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 13,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 14,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 15,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 16,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 17,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 18,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 19,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 20,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 21,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 22,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 23,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 24,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
  {
    topic_id: 25,
    title: "Test-Front",
    created_at: "2021-12-01",
    updated_at: "2021-12-01",
    author: "Test User",
    tags: "Tags go here",
    category: "Test-Back",
    post_id: 22,
    deck_back: "https://client-a785.onrender.com/images/topicDeck_back.jpg",
    image_front: "https://client-a785.onrender.com/images/games_TableTop.jpeg",
  },
];

export default topic_data;
